# Generated by Django 3.0.2 on 2020-06-15 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('photo_user', models.ImageField(default='img/photo_user/default.png', upload_to='img/photo_user/')),
                ('gender', models.CharField(blank=True, choices=[('0', ''), ('1', 'Мужчина'), ('2', 'Женьшина')], default='', max_length=1, null=True)),
                ('about_myself', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', ''), ('1', 'Не женат'), ('2', 'Встречаюсь'), ('3', 'Женат'), ('4', 'Влюблён'), ('5', 'Всё сложно'), ('6', 'В активном поиске')], default='', max_length=1, null=True)),
                ('year_of_birth', models.DateField(blank=True, default=datetime.date(2000, 4, 15), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('friends', models.ManyToManyField(related_name='freands', to=settings.AUTH_USER_MODEL)),
                ('request_friends', models.ManyToManyField(related_name='add_freands', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserData'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
